# Generated by Django 3.2.6 on 2021-08-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('ano', models.IntegerField()),
                ('descricao', models.TextField()),
                ('vendido', models.BooleanField()),
            ],
        ),
    ]
