export const CAR_BRANDS = {
    Fiat: 'Fiat',
    Volkswagen: 'Volkswagen',
    Chevrolet: 'Chevrolet',
    Hyundai: 'Hyundai',
    Toyota: 'Toyota',
    Jeep: 'Jeep',
    Renault: 'Renault',
    Honda: 'Honda',
    Nissan: 'Nissan',
    Ford: 'Ford',
    CAOA_Chery: 'CAOA Chery',
    Peugeot: 'Peugeot',
    Citroen: 'Citroën',
    Mitsubishi: 'Mitsubishi',
    BMW: 'BMW',
    Mercedes_Benz: 'Mercedes-Benz',
    Volvo: 'Volvo',
    Audi: 'Audi',
    Land_Rover: 'Land Rover',
    Kia: 'Kia',
    RAM: 'RAM',
    Porsche: 'Porsche',
    Iveco: 'Iveco',
    Suzuki: 'Suzuki',
    Troller: 'Troller',
    Mini: 'Mini',
    JAC: 'JAC',
    Effa: 'Effa',
    Subaru: 'Subaru',
    Lexus: 'Lexus',
    Jaguar: 'Jaguar',
    Foton: 'Foton',
    BYD: 'BYD',
    Ferrari: 'Ferrari',
    McLaren: 'McLaren',
    Maserati: 'Maserati',
    Lifan: 'Lifan',
    Lamborghini: 'Lamborghini',
    Exeed: 'Exeed',
    SsangYong: 'SsangYong',
    Rolls_Royce: 'Rolls-Royce',
    Agrale: 'Agrale',
    Aston_Martin: 'Aston Martin'
};